vpr_nodes:
  launch_step: 0
  feature_type: RAW
  img_dims:
  - 64
  - 64
  npz_dbp: /data/compressed_sets
  svm_dbp: /cfg/svm_models
  bag_dbp: /data/rosbags

  odom_topic: /odom
  img_topic: /ros_indigosdk_occam/stitched_image0/compressed

  groundtruth: true
  path: 
    bag_name: s3_ccw_1
    odom_topic: /odom
    img_topic: /ros_indigosdk_occam/stitched_image0/compressed

  cal:
    qry:
      bag_name: s3_cw_1
      filters: '{}'
      sample_rate: 10.0
    ref:
      bag_name: s3_cw_f8
      filters: '{}'
      sample_rate: 10.0

  ref:
    bag_name: s3_ccw_f8
    filters: '{}'
    sample_rate: 10.0

  tolerance:
    mode: METRE_LINE
    threshold: 0.2

  svm_trainer:
    log_level: 2
    rate: 12.0

  throttle:
    log_level: 2
    rate: 10.0

  param_watcher:
    log_level: 1
    rate: 2.0

  img_odom_agg:
    log_level: 2
    rate: 10.0

  vpr_cruncher:
    log_level: 1
    dvc_weight: 1
    rate: 12.0
    time_history_length: 20

  vpr_monitor:
    log_level: 2
    print_prediction: false
    rate: 12.0

  vpr_plotter:
    log_level: 2
    rate: 12.0
