#!/bin/bash

ROOT="$(rospack find aarapsi_robot_pack)"
FILE="$ROOT/cfg/$1"
MAPS="$ROOT/data/maps/"
FILE_LINE="$(cat $FILE | grep $2 | xargs)"
PARAM_RAW=${FILE_LINE#"$2:"}
PARAM="$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'<<<"${PARAM_RAW}")"
printf "$MAPS$PARAM"
