#!/usr/bin/env python3

import sys, signal, subprocess, time, rospy


def signal_handler(sig, frame):
    time.sleep(1)
    subprocess.call("killall -q gzclient & killall -q gzserver", shell=True)
    time.sleep(0.2)
    subprocess.call("killall -9 -q gzclient & killall -9 -q gzserver", shell=True)
    sys.exit(0)

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal_handler)
    rospy.init_node('gazebo_watcher')
    rospy.spin()